In [16]:
import os
os.listdir()

['.anaconda',
 '.conda',
 '.condarc',
 '.continuum',
 '.IBM',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.matplotlib',
 '.ms-ad',
 '.spss',
 '.virtual_documents',
 '3D Objects',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'Desktop',
 'Downloads',
 'Favorites',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TM.blf',
 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'OneDrive - University of Aberdeen',
 'Pictures',
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Untitled.ipynb',
 'Videos']

In [6]:
os.path.exists("/")

True

In [68]:
myList = ["Mike", "Ellie", "Kim", "Luna"] 
myList[0]

'Mike'

In [70]:
myList[1:3]

['Ellie', 'Kim']

In [24]:
import numpy as np
import pandas as pd

In [64]:
myList[::1]

['Mike', 'Ellie', 'Kim', 'Luna', 'Jeff', 'George', 7.4, 2.6]

In [66]:
myList[-1]

2.6

In [32]:
myList[::-1]

['Luna', 'Kim', 'Ellie', 'Mike']

In [38]:
myList[::-2]

['Luna', 'Ellie']

In [72]:
dna_seqs = ['ATGGGACTGCCCTTGATGCCTCACGTATCCAAAAGCGTATCATGGAGCACTCGGAAACGCACTATAGCAATACCAGACCGTGATATACAACCAGATCACTCTACGATTAAACGACTGCGCCGCCGTATTGCGCTGCTTATCCGAGAAGCAGTCCCTCGTGCGACGCAGCACCAAGAACAAGTCTCAGAGTACCTTTGGACGTATGACTTCAGGATCGAGTCGGCGGCTAGGTTCTATGGGGAGCTCCGTGATAGGTCATCTAGACAGGGTGTGTATTATTTGAGAGTAAAACGAAATCCTCCTCGCATGTACGGGTCAATGGAATTCCCGGTCAGA',
            'ATGGACACCTGGACATACTCCCAAGAGGCTGGAGCAGTGCCCCATTCCTCGGTGCCTCAAGTTCTGGGAATGTGCAATCCTCCGCGAGACATTCAAGGTTTCAGACCACGCGATCGGGTTAAGATACTATCTCAAGTACTTCTTTCGTGTAAGGCACCACTAGAATTGCTTACTTATCCAGGCGGACAAACTGCAATCCTATCTTCATGGGGGGTAGATTTACCATTTTGTAAGAATCTAGACGCACCACGTGGGCGTAGCGACAGGGAGACACAATGGAGCTGCATGATATGGCGGGATCCAAGATCCATGGCGAGCGCGTCATACTTTAGGTGC',
            'ATGGTGCGCACGATTGAGTTGGAATTAGTCCCCAGACTGGCGACCATTACATACACCCTCCACCTTCCACGTCGGTTCAGCACGGGGTGGTGTTTCTCTCCAACACGAGGCCCGGGCGAATTAGTATTGATAATGCCTGGGCAGACAGCACTGGCCCGGCAGGAGATACTGGGCGATGGAAGACGTGGGTTAAGGCACGTCGGTTCTCTAGGTTTTCTATACTGGGCACGGAAGTTAGGGGCTAAAGAGCAACATACCTCTCCGCTGTCGGTCGATAGTGAGTCTTGCATAGCGATTGCTAAGAGCCTAGTTAAGCATACTCGTAACCGCGCCGCG',
            'ATGCCTCCCGGTATCGCTGAGGCCCTAGCAAACGCACAGATCAACCAACTTGTGTCTAACGCCATGGGATCTGCCGCATTAGCTAACAATATTACGCCTATAACGCACGGCTTACCTTTCAAATGTGCTGACCAAGTGGCCTCGATACAATTAGGGACTACAGGGGATAGATGTGCAAGTTTGTTTCTATCAGCGCCGGTGATTCTACGACCGTGTAATCAGAGGGCAGCGAAGATGGATAAGGGGTTGACCAACATGCTCAGTAATGATCCAGGAGCCGGTTATGCCATGCGAATATGCATGTGCACAGTAGCCGGGAGAGCTTGTATTCGTATA',
            'ATGACCCCACGCGGACCGTCAGGAGAAATCCTCTCACGGGATCCCGTCACTGTAACGCTCAGGGTCTTACGGCAACTCGAATGCTGTCGAAAATGTGGCAGTCAATCTCTATACCGGGGTCCGAGCTTTTTACATGTAATTTTGCAAGAATTCTTATATAGCACGATGAGACACGTACCCGATCACTTCGCCCAGCATACACTGATTAATACCGTCTATGTGATGTATTTACTTAAGACTCTCGCAACACCCGTGGCTTGGCGAAGTCTATCTGCACTAGTCGGGTCAGCCGTGCGGCGCGCACACACATCAAAGTGGCCGCAGTTGAGCGCAGTG']
len(dna_seqs[0])

336

In [74]:
dna_array = np.ndarray((5, 5, 336))
dna_array

array([[[1.26897556e-311, 1.26897292e-311, 6.95335581e-310, ...,
         1.26898967e-311, 1.26898967e-311, 1.26898967e-311],
        [1.26898967e-311, 1.26898967e-311, 1.26898967e-311, ...,
         1.26997417e-311, 1.26898974e-311, 1.26997417e-311],
        [1.26898974e-311, 1.26898974e-311, 1.26997417e-311, ...,
         1.26997417e-311, 1.26898975e-311, 1.26997417e-311],
        [1.26898975e-311, 1.26997417e-311, 1.26898975e-311, ...,
         6.95322186e-310, 6.95322186e-310, 1.26898976e-311],
        [1.26898976e-311, 1.26898976e-311, 1.26898976e-311, ...,
         1.26898975e-311, 1.26898975e-311, 1.26997417e-311]],

       [[1.26898975e-311, 1.26898975e-311, 1.26997417e-311, ...,
         1.26898974e-311, 1.26898974e-311, 1.26997417e-311],
        [1.26898974e-311, 1.26898974e-311, 1.26997417e-311, ...,
         1.26898975e-311, 1.26898975e-311, 1.26898975e-311],
        [1.26898975e-311, 1.26898975e-311, 1.26898975e-311, ...,
         1.26898971e-311, 1.26898971e-311, 1.269974

In [78]:
dna_array = np.zeros((5, 5, 336))
dna_array

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])

In [98]:
dna_seqs[0][0]

'A'

In [108]:
len(dna_seqs)

5

In [106]:
range(len(dna_seqs))

range(0, 5)

In [104]:
for idx1 in range(len(dna_seqs)):
    seq1 = dna_seqs[idx1]
    print(seq1)
    break

ATGGGACTGCCCTTGATGCCTCACGTATCCAAAAGCGTATCATGGAGCACTCGGAAACGCACTATAGCAATACCAGACCGTGATATACAACCAGATCACTCTACGATTAAACGACTGCGCCGCCGTATTGCGCTGCTTATCCGAGAAGCAGTCCCTCGTGCGACGCAGCACCAAGAACAAGTCTCAGAGTACCTTTGGACGTATGACTTCAGGATCGAGTCGGCGGCTAGGTTCTATGGGGAGCTCCGTGATAGGTCATCTAGACAGGGTGTGTATTATTTGAGAGTAAAACGAAATCCTCCTCGCATGTACGGGTCAATGGAATTCCCGGTCAGA


In [86]:
for idx1 in range(len(dna_seqs)):
    seq1 = dna_seqs[idx1]
    for idx2 in range(len(dna_seqs)):
        seq2 = dna_seqs[idx2]
        for nt in range(len(seq1)):
            if seq1[nt] == seq2[nt]:
                dna_array[idx1, idx2, nt] = 1
            else:
                dna_array[idx1, idx2, nt] = 0

In [88]:
dna_array[1, 1, :]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [92]:
dna_array[1, 2, :]

array([1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0.,
       1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0.,
       0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1.,
       0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1.,
       1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0.

In [118]:
np.sum(dna_array[1,2,:])

90.0

In [183]:
np.sum(dna_array[:, :, 99])

9.0

In [130]:
phone_book = {"Names": ["Mike", "Daniel", "Ellie", "Heather"],
             "Office": ["6.17", "5.23", "3.20", "3.18"],
             "Department": ["Immunology", "Neuroscience", "Developmental Biology", "Immunology"]}
pb_df = pd.DataFrame(phone_book)
print(pb_df)

     Names Office             Department
0     Mike   6.17             Immunology
1   Daniel   5.23           Neuroscience
2    Ellie   3.20  Developmental Biology
3  Heather   3.18             Immunology


In [132]:
pb_df.shape

(4, 3)

In [134]:
pb_df.set_index("Names")

Office             Department
Names                                
Mike      6.17             Immunology
Daniel    5.23           Neuroscience
Ellie     3.20  Developmental Biology
Heather   3.18             Immunology

In [146]:
pb_df.iloc[:, 0] == pb_df["Names"]

0    True
1    True
2    True
3    True
Name: Names, dtype: bool

In [154]:
pb_df.set_index("Names", inplace=True, drop=False)
pb_df

Names Office             Department
Names                                         
Mike        Mike   6.17             Immunology
Daniel    Daniel   5.23           Neuroscience
Ellie      Ellie   3.20  Developmental Biology
Heather  Heather   3.18             Immunology

In [156]:
pb_df.loc["Mike", :]

Names               Mike
Office              6.17
Department    Immunology
Name: Mike, dtype: object

In [158]:
pb_df.loc[["Mike", "Heather"], :]

Names Office  Department
Names                              
Mike        Mike   6.17  Immunology
Heather  Heather   3.18  Immunology

In [164]:
phone_list = {"Names": ["Mike", "Daniel", "Ellie", "Heather"],
             "Office": ["6.17", "5.23", "3.20", "3.18"],
             "Department": ["Immunology", "Neuroscience", "Developmental Biology", "Immunology"]}
list_df = pd.DataFrame(phone_list)
list_df

Names Office             Department
0     Mike   6.17             Immunology
1   Daniel   5.23           Neuroscience
2    Ellie   3.20  Developmental Biology
3  Heather   3.18             Immunology

In [171]:
import re

In [173]:
tata_re = re.compile("TATA[A|T]A[A|T]")
tata_re

re.compile(r'TATA[A|T]A[A|T]', re.UNICODE)

In [175]:
bact_seq = "CACTTCAGGTTAAGCGGCGCGGCCTGCGCATTTTGGATATATATAATCCT"
tata_match = tata_re.search(bact_seq)
tata_match

<re.Match object; span=(37, 44), match='TATATAT'>

In [177]:
tata_idx = tata_match.span()
bact_seq[tata_idx[0]:tata_idx[1]]

'TATATAT'

In [179]:
tata_match.group(0)

'TATATAT'

In [2]:
print("test")

test
